### ISSUE TITLE
Bug: Deletion of SIB results in crash

### ISSUE THREAD

**Issue by anurag-rajawat** [5GSEC/nimbus#28]
## Description
After successfully applying the SecurityIntent (SI) and SecurityIntentBinding (SIB), if we try to delete the SIB then nimbus crashes. However, SIB gets deleted from the k8s API server. 

## Steps to reproduce
1. Run nimbus `make run`
2. Start HTTP server `go run pkg/nimbus-kubearmor/receiver/server/server.go`
3. Apply SI and SIB 
4. Delete SIB
And then the nimbus crashes.

## Expected behaviour
nimbus should not crash on the deletion of SIB.

## Additional context
![Screenshot 2024-01-05 at 14 26 11](https://github.com/5GSEC/nimbus/assets/94977678/a7835dad-202a-43fb-8c99-a73860d719df)

**Comment by seungsoo-lee** [comment]
PR #29
